### ISSUE TITLE
Error using F77LBFGSB class in optim.py, '_lbfgsb' has no attribute 'types'

### ISSUE THREAD

**Issue by Jashcraf** [brandondube/dygdug#14]
Attempting to use the F77LBFGSB class with the VAPPOptimizer. Encountering an error at this line in the class

[`fint_dtype = _lbfgsb.types.intvar.dtype`](https://github.com/brandondube/dygdug/blob/5bf0b12038198d2a4e2dd466365e71f747a16db4/dygdug/optim.py#L13)

This is the error:
`AttributeError: module 'scipy.optimize._lbfgsb' has no attribute 'types'`

**Code to Reproduce Error**
```
from prysm import coordinates, geometry
from prysm.propagation import Wavefront as WF
from prysm.polynomials import noll_to_nm,zernike_nm_sequence
rap = 1.25  
x, y = coordinates.make_xy_grid(256, diameter=10)
r, t = coordinates.cart_to_polar(x, y)
dx = x[0,1]-x[0,0]
ap = geometry.circle(rap, r)
ap = ap / np.sqrt(ap.sum())
wvl = 0.551
efl = 100
fno = efl/(2*rap)
lamD = wvl*fno

wf = WF.from_amp_and_phase(ap, None, wvl,  dx)
psf = wf.focus(Q=1, efl=efl).intensity

xx, yy = psf.x, psf.y
xx = xx / lamD
yy = yy / lamD
rr, tt = coordinates.cart_to_polar(xx, yy)

dh_mask = (xx > 2) & (rr<16)

nms = list(noll_to_nm(j) for j in range(4, 250))
basis = np.array(list(zernike_nm_sequence(nms, r/rap, t)))

x0 = np.zeros(len(nms))

ap = geometry.circle(rap, r)
# norm = np.sqrt(vapp.I.max())
# ap = ap / norm
vapp = vap.VAPPOptimizer(ap, wvl, basis, dh_mask, dh_target=0)
result = vapp.fg(x0)

opt = F77LBFGSB(vapp.fg, x0, memory=50)
```

**Comment by Jashcraf** [comment]
set `fint_dtype = np.int32` and the block of code *ran*, but unsure if that's the correct data type.

**Comment by brandondube** [comment]
which version of scipy?  What does

```python
from scipy.optimize import _lbfgsb
print(dir(_lbfgsb))
```
show?

**Comment by Jashcraf** [comment]
<img width="874" alt="image" src="https://user-images.githubusercontent.com/25557892/206828578-3162265f-9c46-449f-96f5-edcb358b882f.png">

**Comment by brandondube** [comment]
Perhaps you could update to a newer version?  1.4.1 is about 3 years out of date, 1.9.3 is current.  I'm not sure when the types stuff was added

**Comment by Jashcraf** [comment]
That fixed it!
